baseURL = 'https://robertluwang.github.io/artark-ai/'
defaultContentLanguage = 'en'
title = 'Artark AI'
theme = 'papermod'

[params]
  env = "production"
  title = "Artark AI"
  description = "Minimal AI tech notes and code snippets"
  author = "robertluwang"
  showReadingTime = true
  showShareButtons = true
  showPostNavLinks = true
  showTags = true
  
[outputs]
  home = [ "HTML", "RSS", "JSON"]
