baseURL = 'https://robertluwang.github.io/artark-ai/'
defaultContentLanguage = 'en'
title = 'My Tech Blog'
theme = 'papermod'

[params]
  env = "production"
  title = "My Tech Blog"
  description = "Minimal tech notes and code snippets"
  author = "Me"
  showReadingTime = true
  showShareButtons = true
  showPostNavLinks = true
  showTags = true
  
[outputs]
  home = [ "HTML", "RSS", "JSON"]
